name: Feature Request
description: Suggest an idea for OpenTelemetry Android
title: "Feature: [Brief Description]"
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out this form to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would help
      placeholder: |
        Explain how this feature would be used and what benefits it would provide.

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
        - OpenTelemetry Android version
        - Android API level / OS version
        - Device (if applicable)
        - Gradle version
        - Build tools version
      placeholder: |
        - OpenTelemetry Android version:
        - Android API level:
        - Android OS version:
        - Device:
        - Gradle version:
        - Build tools version:

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context or screenshots about the feature request here.

  - type: dropdown
    attributes:
      label: Tip
      description: |
        This element is static, used to render a helpful sub-heading for end-users
        and community members to help prioritize issues. Please leave as is.
      options:
        - |
          <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0
