name: Question
description: Ask a question about OpenTelemetry Android
title: "Question: [Brief Description]"
labels: ["question", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for asking a question! Please fill out this form to help us provide the best assistance.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe your question clearly
      placeholder: What would you like to know about OpenTelemetry Android?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Please provide context about what you're trying to accomplish
      placeholder: What are you trying to achieve? What have you already tried?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Examples
      description: Please provide relevant code examples or configuration
      render: kotlin

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
        - OpenTelemetry Android version
        - Android API level / OS version
        - Device (if applicable)
        - Gradle version
        - Build tools version
      placeholder: |
        - OpenTelemetry Android version:
        - Android API level:
        - Android OS version:
        - Device:
        - Gradle version:
        - Build tools version:

  - type: textarea
    id: research
    attributes:
      label: Research Done
      description: What documentation, examples, or resources have you already checked?
      placeholder: |
        - OpenTelemetry documentation:
        - GitHub issues/discussions:
        - Stack Overflow:
        - Other resources:

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about your question here.

  - type: dropdown
    attributes:
      label: Tip
      description: |
        This element is static, used to render a helpful sub-heading for end-users
        and community members to help prioritize issues. Please leave as is.
      options:
        - |
          <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0
